!include ../../../styles/PlantUML_StyleSheet.puml

actor 사용자 as user
participant 클라이언트 as client #9EA0CA
participant CLOVA as clova #05D686


  client -> client : 알람 시작
  client ->> clova : 알람 시작 보고\n(Alerts.AlertStarted 이벤트 메시지,\lAlert.AlertsState에 activateAlerts 필드 필수 포함)

  activate clova
  deactivate clova

  user ->> client : 알람 중지 요청 (발화 또는 물리버튼)

  alt 알람 중지 요청 유형 == 사용자 발화

    client ->> clova : 알람 중지 요청 전달\n(SpeechRecognizer.Recognize 이벤트 메시지)

  activate clova

  else 알람 중지 요청 유형 == 물리 버튼

    client ->> clova : 알람 중지 요청 전달\n(Alerts.RequestAlertStop 이벤트 메시지)

  end

  clova -->> client : Alerts.StopAlert 지시 메시지 전달

  deactivate clova

  client ->> clova : 알람 중지 결과 보고\n(Alerts.AlertStopped 이벤트 메시지)
  
  activate clova

    opt 반복 알람 여부 == 네

      clova -->> client : 다음 반복 알람 전달\n(Alerts.SetAlert 지시 메시지)

    end

    opt 알람 종류 == 액션타이머

      clova -->> client : 사용자가 예약한 동작을 수행하는 지시 메시지 전달

    deactivate clova

      client -> client : 예약된 동작 수행

    end

  deactivate client
  deactivate clova
